services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: tearsthemoon
    ports:
      - "3306:3306"
    volumes:
      - ./db/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql 
      - mariadb_data:/var/lib/mysql
    networks:
      - redEAT

  couchbase:
    user: root  
    image: couchbase:latest
    container_name: couchbase
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"  
      - "8094:8094"  
      - "11210:11210"  
    volumes:
      - ./db/couchbase/colecciones/init.sh:/init.sh
      - ./db/couchbase/colecciones/index.sh:/index.sh
      - ./db/couchbase/colecciones/entrypointNew.sh:/entrypointNew.sh
      - couchbase_data:/opt/couchbase/var
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=administrador
      - COUCHBASE_ADMINISTRATOR_PASSWORD=tearsthemoon
    entrypoint: ["/bin/bash","/entrypointNew.sh"]
    command: ["couchbase-server"]
    networks:
      - redEAT

  autentificacion:
    build:
      context: ./backend/auth  
      dockerfile: Dockerfile
    container_name: autentificacion
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./backend/auth:/app
    depends_on:
      - mariadb
      - couchbase
    networks:
      - redEAT

  libreria:
    build:
      context: ./backend/library 
      dockerfile: Dockerfile
    container_name: libreria
    restart: on-failure
    ports:
      - "8081:8081"
    volumes:
      - ./backend/library:/app
    depends_on:
      - mariadb
      - couchbase
    networks:
      - redEAT

  #frontea
  
  #  build:
  #    context: ./frontend/EduAndTime
  #    dockerfile: Dockerfile
  #  container_name: frontEAT
  #  ports:
      #- "80:80"
  #  depends_on:
  #    - mariadb
  #    - couchbase
  #    - autentificacion
  #  networks:
  #    - redEAT

volumes:
  couchbase_data: # Este es el volumen para almacenar datos persistentes de Couchbase
    driver: local
  mariadb_data: # Volumen persistente para MariaDB
    driver: local

networks:
  redEAT:
    driver: bridge
