// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type TokenAuth struct {
	Token   *string  `json:"Token,omitempty"`
	Usuario *Usuario `json:"Usuario,omitempty"`
	Exito   bool     `json:"Exito"`
	Expira  *int64   `json:"Expira,omitempty"`
}

type Usuario struct {
	Nombre  string  `json:"Nombre"`
	Correo  string  `json:"Correo"`
	ImgPerf *string `json:"ImgPerf,omitempty"`
}
